BEGIN;

CREATE TABLE IF NOT EXISTS car_models (
    id_car_model INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(120) NOT NULL,
    model_year SMALLINT NOT NULL CHECK (model_year BETWEEN 1886 AND 2100),
    base_price NUMERIC(12,2) NOT NULL CHECK (base_price >= 0),
    description TEXT,
    main_image_url TEXT,
    fuel_capacity INTEGER CHECK (fuel_capacity >= 0),
    horse_power INTEGER CHECK (horse_power >= 0),
    v_max INTEGER CHECK (v_max >= 0),
    acceleration DOUBLE PRECISION CHECK (acceleration >= 0),
    cylinders INTEGER CHECK (cylinders >= 0),
    fuel_type VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS model_configurations (
    id_model_configuration INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_model_id INTEGER NOT NULL,
    configuration_name VARCHAR(120) NOT NULL,
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    description TEXT,
    equipment TEXT,
    fuel_type VARCHAR(50),
    image_url TEXT,
    trunk_volume DOUBLE PRECISION CHECK (trunk_volume >= 0),
    acceleration DOUBLE PRECISION CHECK (acceleration >= 0),
    CONSTRAINT fk_model_configurations_car_model
        FOREIGN KEY (car_model_id)
        REFERENCES car_models (id_car_model)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS used_cars (
    id_used_car INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(120) NOT NULL,
    odometer_km INTEGER NOT NULL CHECK (odometer_km >= 0),
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    color VARCHAR(50),
    engine VARCHAR(100),
    fuel_type VARCHAR(50),
    description TEXT,
    main_image_url TEXT,
    model_year SMALLINT CHECK (model_year BETWEEN 1886 AND 2100),
    horse_power INTEGER CHECK (horse_power >= 0),
    drivetrain VARCHAR(50),
    transmission VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS financing_requests (
    id_financing_request INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    interest_model VARCHAR(120) NOT NULL,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id_newsletter_subscriber INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    subscribed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS appointments (
    id_appointment INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    appointment_date TIMESTAMPTZ NOT NULL,
    interest_model VARCHAR(120) NOT NULL,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_car_models_name
    ON car_models(model_name);

CREATE INDEX IF NOT EXISTS idx_car_models_year
    ON car_models(model_year);

CREATE INDEX IF NOT EXISTS idx_model_configurations_car_model_id
    ON model_configurations(car_model_id);

CREATE INDEX IF NOT EXISTS idx_used_cars_model_name
    ON used_cars(model_name);

CREATE INDEX IF NOT EXISTS idx_used_cars_model_year
    ON used_cars(model_year);

CREATE INDEX IF NOT EXISTS idx_used_cars_price
    ON used_cars(price);

CREATE INDEX IF NOT EXISTS idx_used_cars_odometer_km
    ON used_cars(odometer_km);

CREATE INDEX IF NOT EXISTS idx_financing_requests_email
    ON financing_requests(email);

CREATE INDEX IF NOT EXISTS idx_appointments_date
    ON appointments(appointment_date);

CREATE INDEX IF NOT EXISTS idx_appointments_email
    ON appointments(email);

COMMIT;